//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleaningServices1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int Rating1 { get; set; }
        public int RatingID { get; set; }
        public string Comment { get; set; }
        public int BookingID { get; set; }
    
        public virtual Booking Booking { get; set; }
    }
}
